### ISSUE TITLE
[Suggestion]: change note linking syntax

### ISSUE THREAD

**Issue by neraid-live** [nvim-neorg/norg-specs#40]
Right now, linking to other notes feels much like a chore, especially when `:` isn't considered an encapsulation character by most. Two levels of encapsulation for note linking hurts the ergonomy, in my honest opinion.

Maybe something like {& $/This is a note}, which follows the the {`type` `link`} convention.

**Comment by mrossinek** [comment]
The `:` is getting some updates: #36. Does that address some/all of your points?

**Comment by neraid-live** [comment]
> The `:` is getting some updates: #36. Does that address some/all of your points?

Actually, yes! For the most part. My primary concern was with the encapsulation. My only other issue is that `:` is an uncommon choice for this purpose, but then again, it is *difficult* to create unambigous syntax for everything without recurring to less commonly used characters.
