### ISSUE TITLE
 inline code syntax highlighting

### ISSUE THREAD

**Issue by aabbccddeeffggj** [nvim-neorg/norg-specs#45]
1 - On a .norg file:
```
- example of initializing a variable:
@inline(cpp) int two{2};
```
concealing...
```cpp
• example of initializing a variable
int two{2};
```

2 - Being able to define aliases for these statements would be interesting:
```
/alias("@inline(cpp)", "cpp")
```
```
- example of initializing a variable
cpp int two{2};
```
concealing...
```cpp
• example of initializing a variable
int two{2};
```

**Comment by boltlessengineer** [comment]
We already have this feature with attached modifier extension:
```
`int two{2};`(lang:cpp)
```

https://github.com/nvim-neorg/norg-specs/blob/82d7f7fa066066b997056bfdb1ab30ca336307e8/1.0-specification.norg#L1244-L1250

**Comment by aabbccddeeffggj** [comment]
It has yet to be implemented in the future? I tested it and doesn't seem to work.

**Comment by boltlessengineer** [comment]
It is working as a spec since you can see it from syntax tree.
If you mean you can’t see highlights from neorg, then that’s neorg’s problem.
Its been a while since I really used neorg, but I remember it is not supported due to performance issue, at least it is disabled by default.

**Comment by aabbccddeeffggj** [comment]
I see, thanks for the information.
