### ISSUE TITLE
Paragraph break

### ISSUE THREAD

**Issue by dwarfmaster** [nvim-neorg/norg-specs#8]
Looking at the spec, I noticed that a line made only of whitespace does not count as a paragraph break. This means that attached modifiers should carry over that, and I have confirmed that the treesitter parser indeed does not break the paragraph over a white line. I think this is surprising, especially considering the intent to have leading white space in line irrelevant, so maybe this should be changed ?

**Comment by mrossinek** [comment]
Hi there! Thanks for bringing this to our attention!

Indeed I agree that a line which only contains whitespace should be considered a valid paragraph break. I just opened PR #9 to propose a fix for this in the spec :+1:
